### ISSUE TITLE
Find design patterns that would help with the implementation of tasks. 

### ISSUE THREAD

**Issue by collinarnett** [collinarnett/PersonalGamification#18]
We know that we want a task class.

Now to figure out how to implement it.

Report back with a design pattern that would help implement the task class. Mention why you chose that design pattern and briefly describe the implementation.

**Comment by abene86** [comment]
If we can have a task manager object and a separate object of the task itself,  with all the behavior we defined creating a task, deleting a task, modifying a task, and listing a task attached to the task manager object, which has data structure/database. The singleton design pattern will be helpful for the case because it will allow us to have one global instance of task manager object where we can interact with task objects.

**Comment by abene86** [comment]
To add to what I wrote:  task manager we will have a private constructor and static method to create only one instance. we can get access to that instance using the get instance method(). The benefits is it going to be very easy to implement create, delete,  list,  adjust, and complete tasks; we just need a way to uniquely id each task and place them in data struct/database. The downside is the task object is going to be abstracted away inside the task manager object. It might be messy to interact with the event and player object.

**Comment by abene86** [comment]
Most of the patterns I have read in the book are geared OOP, but I was able to find a use for the strategy patterns in the context of functional programming. Here is the reading for it: https://dev.to/qgabe/functional-programming-design-patterns-part-1-strategy-pattern-4f92. I choose this pattern because depending on the context which is our input from the command line, the strategy function will choose from different functions which are appropriate to use.  For the implementation, it requires us to use interface the strategy. I think we don't need it for our case; we can loosely adapt this pattern and still get its core ideas: the context being the input/command, the strategy is a function that takes the input and decides which appropriate function to run,  and all the algos could be our functions for our task.  The only part on we could discuss is how we are going to save the tasks.

**Comment by collinarnett** [comment]
Could you write some pseudo-code for how this would work? @abene86

**Comment by abene86** [comment]
main(args)
     loop(){
	// Input from the command line
	// args  already parsed and ready to be used
	// command name
// other information from the command line
//Call funct strategy( takes in the command name) returns a number
//enum 1 can be used to represent created,  2 can be deleted 3 can be //completed 4 can be listed a task 5 can be  adjusted task
		// we can add other commands.
	if(number matches 1)
		Call createtask(other information from the command line)
	Else if(number matches 2)
		Call delete task(other information from the command line)
	Else if
	.
	.
	.	
	.	
	.	
	.
	}

**Comment by collinarnett** [comment]
I still don't really understand what's happening here. Can you make your pseudo code more scala-like?

**Comment by abene86** [comment]
def main(args: Array[String])
     while(true){
		//parsing the command line input
		.
		.
		.
// based on the command name it will decide which function to call
val number = strategy( String: commandname, String[option] mode)
//1 represent creat task, 2 delete, 3 lists…
	if(number == 1)
		 createTask(String: other information from the command line like task name, due date, description)
	else if(number ==  2)
	 	deleteTask(Integer: id of the task)
	else if(number == 3)
		listTask(String: other information like flags);
		
	.
	.
	.	
	.	
	.	
	}
How about now?

**Comment by collinarnett** [comment]
We decided to load the parameters from the argument parser directly into the task class. This solves our issues for now.
